export const FETCH_ITEM_METADATA_INITIAL = 'FETCH_ITEM_METADATA_INITIAL';
export const FETCH_ITEM_METADATA_SUCCESS = 'FETCH_ITEM_METADATA_SUCCESS';
export const FETCH_ITEM_METADATA_FAILURE = 'FETCH_ITEM_METADATA_FAILURE';

export const FETCH_BID_INITIAL = 'FETCH_BID_INITIAL';
export const FETCH_BID_SUCCESS = 'FETCH_BID_SUCCESS';
export const FETCH_BID_FAILURE = 'FETCH_BID_FAILURE';

export const PLACE_BID_INITIAL = 'PLACE_BID_INITIAL';
export const PLACE_BID_SUCCESS = 'PLACE_BID_SUCCESS';
export const PLACE_BID_FAILURE = 'PLACE_BID_FAILURE';

export const FETCH_NFT_PRICE_INITIAL = 'FETCH_NFT_PRICE_INITIAL';
export const FETCH_NFT_PRICE_SUCCESS = 'FETCH_NFT_PRICE_SUCCESS';
export const FETCH_NFT_PRICE_FAILURE = 'FETCH_NFT_PRICE_FAILURE';
